import os
import json
import numpy as np
import pandas as pd
import joblib
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import roc_auc_score, f1_score, precision_score, recall_score, confusion_matrix

def fit_real_preprocessing(dataset_name, seed):
    """
    Reconstructs the raw training split for the given seed and fits all necessary
    preprocessing transformers (imputers, encoders, scalers) on it.
    """
    if dataset_name == "german_credit":
        raw_path = "data/raw/german_credit.csv"
        target = 'class'
    elif dataset_name == "gmsc":
        raw_path = "data/raw/gmsc_sampled_10k.csv"
        target = 'SeriousDlqin2yrs'
    else:
        raise ValueError(f"Unknown dataset: {dataset_name}")
        
    df = pd.read_csv(raw_path)
    if dataset_name == "gmsc" and "Unnamed: 0" in df.columns:
        df = df.drop(columns=["Unnamed: 0"])
        
    X = df.drop(columns=[target])
    y = df[target]
    
    # Stratified split matching Phase 1/2
    X_train, _, _, _ = train_test_split(
        X, y, test_size=0.3, stratify=y, random_state=seed
    )
    
    # Identify feature types
    num_cols = X_train.select_dtypes(include=['int64', 'float64']).columns.tolist()
    cat_cols = X_train.select_dtypes(include=['object', 'category']).columns.tolist()
    
    # Fit Imputers
    num_imputer = SimpleImputer(strategy='median')
    num_imputer.fit(X_train[num_cols])
    X_train_num_imp = num_imputer.transform(X_train[num_cols])
    
    scaler = StandardScaler()
    scaler.fit(X_train_num_imp)
    
    encoders = {}
    cat_imputer = None
    if len(cat_cols) > 0:
        cat_imputer = SimpleImputer(strategy='most_frequent')
        X_train_cat_imp = cat_imputer.fit_transform(X_train[cat_cols])
        X_train_cat_df = pd.DataFrame(X_train_cat_imp, columns=cat_cols, index=X_train.index)
        for col in cat_cols:
            le = LabelEncoder()
            le.fit(X_train_cat_df[col])
            encoders[col] = le
            
    return {
        "num_imputer": num_imputer,
        "cat_imputer": cat_imputer,
        "scaler": scaler,
        "encoders": encoders,
        "num_cols": num_cols,
        "cat_cols": cat_cols,
        "original_columns": X.columns.tolist()
    }

def preprocess_synthetic_data(df_synthetic, dataset_name, fitted, target_column):
    """
    Preprocesses raw synthetic data using transformers pre-fit on real training data.
    Gracefully handles unseen categories in synthetic columns.
    """
    df = df_synthetic.copy()
    
    X = df.drop(columns=[target_column])
    y = df[target_column]
    
    # 1. Impute and scale numerical features
    X_num = pd.DataFrame(fitted["num_imputer"].transform(X[fitted["num_cols"]]), 
                         columns=fitted["num_cols"], index=X.index)
    X_num_scaled = pd.DataFrame(fitted["scaler"].transform(X_num), 
                                columns=fitted["num_cols"], index=X.index)
    
    # 2. Impute and encode categorical features
    X_cat_enc = pd.DataFrame(index=X.index)
    if len(fitted["cat_cols"]) > 0:
        # Impute
        X_cat_imp = fitted["cat_imputer"].transform(X[fitted["cat_cols"]])
        X_cat_df = pd.DataFrame(X_cat_imp, columns=fitted["cat_cols"], index=X.index)
        # Encode
        for col in fitted["cat_cols"]:
            le = fitted["encoders"][col]
            known_classes = set(le.classes_)
            # Handle unseen categories generated by CTGAN/TVAE (fallback to mode/first class)
            fallback = le.classes_[0]
            X_cat_df[col] = X_cat_df[col].apply(lambda x: x if x in known_classes else fallback)
            X_cat_enc[col] = le.transform(X_cat_df[col])
            
    # 3. Combine features, keeping original order
    X_proc = pd.concat([X_num_scaled, X_cat_enc], axis=1)[fitted["original_columns"]]
    
    # 4. Target mapping
    if dataset_name == "german_credit":
        y_proc = y.map({'good': 0, 'bad': 1}).astype(int)
    else:
        # SeriousDlqin2yrs is binary categories, but force to int type
        y_proc = y.astype(int)
        
    return X_proc, y_proc

def train_synthetic_model(
    X_train_syn, y_train_syn, X_test_real, y_test_real, 
    params, dataset_name, generator_type, seed, 
    model_dir="models/", results_dir="results/"
):
    """
    Trains XGBoost classifier on preprocessed synthetic training split, evaluates
    on real test split, and saves prediction files and model artifacts.
    """
    print(f"Training XGBoost on {generator_type.upper()} synthetic data for {dataset_name} (Seed {seed})...")
    
    # Dynamic scale_pos_weight
    num_neg = (y_train_syn == 0).sum()
    num_pos = (y_train_syn == 1).sum()
    # Handle edge case where no positive samples are generated
    scale_pos_weight = num_neg / num_pos if num_pos > 0 else 1.0
    
    model = xgb.XGBClassifier(
        **params,
        scale_pos_weight=scale_pos_weight,
        eval_metric='auc',
        random_state=seed,
        use_label_encoder=False
    )
    
    model.fit(X_train_syn, y_train_syn)
    
    # Evaluate on real test split
    y_pred = model.predict(X_test_real)
    y_pred_proba = model.predict_proba(X_test_real)[:, 1]
    
    roc_auc = roc_auc_score(y_test_real, y_pred_proba)
    f1 = f1_score(y_test_real, y_pred)
    precision = precision_score(y_test_real, y_pred, zero_division=0)
    recall = recall_score(y_test_real, y_pred, zero_division=0)
    cm = confusion_matrix(y_test_real, y_pred)
    
    tn, fp, fn, tp = cm.ravel()
    
    metrics = {
        "dataset": dataset_name,
        "seed": seed,
        "parameters": params,
        "roc_auc": float(roc_auc),
        "f1": float(f1),
        "precision": float(precision),
        "recall": float(recall),
        "confusion_matrix": [[int(tn), int(fp)], [int(fn), int(tp)]]
    }
    
    # Save the model
    os.makedirs(os.path.join(model_dir, generator_type), exist_ok=True)
    model_path = os.path.join(model_dir, generator_type, f"{dataset_name}_{generator_type}_xgboost_seed{seed}_v1.joblib")
    joblib.dump(model, model_path)
    print(f"Saved synthetic-trained model to {model_path}")
    
    # Save test set predictions (probabilities and labels)
    os.makedirs(os.path.join(results_dir, generator_type), exist_ok=True)
    preds_df = pd.DataFrame({
        "y_true": y_test_real.ravel(),
        "y_pred": y_pred,
        "y_prob": y_pred_proba
    })
    preds_path = os.path.join(results_dir, generator_type, f"{dataset_name}_{generator_type}_xgboost_seed{seed}_v1_predictions.csv")
    preds_df.to_csv(preds_path, index=False)
    print(f"Saved real test predictions to {preds_path}")
    
    return model, metrics
